version: '3.9'
services:
  php-fpm:
    build:
      context: "./vendor/pipo/raft/services/php83"
    volumes:
      - ./:/var/www/html:rw
    ports:
      - "5173:5173"
    networks:
      - raft
  
  apache-httpd:
    build:
      context: "./vendor/pipo/raft/services/apache"
    volumes:
      - ./:/var/www/html:rw
      - ./docker/apache/ssl:/usr/local/apache2/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - raft

networks:
  raft:
    driver: bridge