version: '3.9'
services:
  php-fpm:
    build:
      context: "./vendor/pipo/raft/services/php83"
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    container_name: "${APP_NAME}-php-fpm"
    volumes:
      - ./:/var/www/html:rw
    links:
      - database
    environment:
      WWWUSER: '${WWWUSER}'
    ports:
      - "5173:5173"
    networks:
      - raft
  apache-httpd:
    build:
      context: "./vendor/pipo/raft/services/apache"
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    container_name: "${APP_NAME}-webserver"
    volumes:
      - ./:/var/www/html:rw
      - ./docker/apache/conf/extra:/usr/local/apache2/conf/extra
    ports:
      - "${APP_UNSECURE_HOST_PORT}:80"
    environment:
      WWWUSER: '${WWWUSER}'
    links:
      - database
    depends_on:
      - php-fpm
    networks:
      - raft
  database:
    build:
      context: "./vendor/pipo/raft/services/mysql8"
      dockerfile: Dockerfile
    container_name: "${APP_NAME}-database"
    restart: "always"
    ports:
      - "127.0.0.1:${database_default_port-3306}:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${database_default_database-db_codeigniter}
      MYSQL_USER: ${database_default_username}
      MYSQL_PASSWORD: ${database_default_password}
    networks:
      - raft
  phpmyadmin:
    image: phpmyadmin
    container_name: "${APP_NAME}-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: ${database_default_port}
      PMA_USER: ${DATABASE_ROOT_USERNAME-root}
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: root${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${database_default_username}
      MYSQL_PASSWORD: ${database_default_password}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    networks:
      - raft
  redis:
    image: redis:latest
    container_name: "${APP_NAME}-redis"
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    networks:
      - raft

networks:
  raft:
    driver: bridge