version: '3'

services:
  raft-app:
    build:
      context: ./vendor/pipo/raft/docker/config/php
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        WWWUSER: '${WWWUSER}'
    image: codeigniter-raft/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
      CODEIGNITER_RAFT: 1
      PHP_IDE_CONFIG: serverName=codeigniter-raft
      SUPERVISOR_PHP_USER: raft
    volumes:
      - '.:/var/www/html'
      - '${COMPOSER_HOME:-$HOME/.composer}:/root/.composer'
    networks:
      - raft
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "php", "artisan", "--version"]
      retries: 3
      timeout: 5s

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-codeigniter}'
      MYSQL_USER: '${DB_USERNAME:-codeigniter}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'raft-mysql:/var/lib/mysql'
      - './vendor/pipo/raft/docker/config/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - raft
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD:-password}"]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - 'raft-redis:/data'
    networks:
      - raft
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - raft
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - '${PHPMYADMIN_PORT:-8080}:80'
    environment:
      PMA_HOST: mysql
      PMA_USER: '${DB_USERNAME:-codeigniter}'
      PMA_PASSWORD: '${DB_PASSWORD:-password}'
      UPLOAD_LIMIT: 300M
    networks:
      - raft
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      retries: 3
      timeout: 5s

networks:
  raft:
    driver: bridge

volumes:
  raft-mysql:
    driver: local
  raft-redis:
    driver: local
